[package]
name = "substrait-expr"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
description.workspace = true

include = [
    "build.rs",
    "src/**/*.rs",
    "tests/**/*.rs",
    "substrait/LICENSE",
    "substrait/README.md",
    "substrait/extensions/**/*.yaml",
]

[dependencies]
substrait.workspace = true
thiserror = "1.0.50"
substrait-expr-macros.workspace = true
once_cell = "1.19.0"
prost = "0.12.3"

[build-dependencies]
substrait-expr-funcgen.workspace = true
