[project]
name = "substrait_expr"
description = "Create and use substrait expressions"
requires-python = ">=3.10"

[build-system]
requires = ["maturin>=1.0.0"]
build-backend = "maturin"

[tool.maturin]
module-name = "substrait_expr._internal"
python-source = "python"
