name: Rust

on:
  pull_request:

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - uses: mbrobbel/rustfmt-check@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          mode: review
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - uses: giraffate/clippy-action@v1
        with:
          clippy_flags: -- -Dwarnings
          reporter: "github-pr-review"
          github_token: ${{ secrets.GITHUB_TOKEN }}
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
      - uses: dtolnay/rust-toolchain@nightly
      - uses: taiki-e/install-action@nextest
      - name: Run tests
        run: cargo nextest run
        env:
          CARGO_TERM_COLOR: always
